version: "3.9"

services:
  api:
    build: .
    container_name: fastapi_app
    ports:
      - "8002:8000"
    volumes:
      - ./app/src/:/app/
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "user"
      POSTGRES_DB: "db"

volumes:
  postgres_data: